import fs from "fs";
import path from "path";
import yaml from "js-yaml";
import crypto from "crypto";

const SPEC_FILE = "tsp-output/schema/openapi.1.0.0.yaml";
const OUTPUT_DIR = "yaak";
const WORKSPACE_NAME = "Core System";
const WORKSPACE_DESCRIPTION = "Core System API (autogenerated)";
const fmtDate = (d = new Date()) => {
    const pad = (n, len = 2) => String(n).padStart(len, "0");
    return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}:${pad(d.getSeconds())}`;
};
const NOW = date => fmtDate(date ? new Date(date) : undefined);

// ----------  helpers ----------
const id = (pfx, seed) => {
    const hash = crypto.createHash("sha256").update(seed).digest("base64url");
    return `${pfx}_${hash.slice(0, 10)}`;
};

// Resolve $ref in schema
const resolveRef = (ref, spec) => {
    if (!ref || !ref.startsWith("#/")) return null;
    const path = ref.substring(2).split("/");
    let result = spec;
    for (const part of path) {
        result = result[part];
        if (!result) return null;
    }
    return result;
};

// Extract example from schema
const getSchemaExample = (schema, spec) => {
    if (!schema) return null;

    // Check if schema has $ref
    if (schema.$ref) {
        const resolved = resolveRef(schema.$ref, spec);
        if (resolved) {
            return getSchemaExample(resolved, spec);
        }
    }

    // Check for examples array
    if (schema.examples && Array.isArray(schema.examples) && schema.examples.length > 0) {
        return schema.examples[0];
    }

    // Check for single example
    if (schema.example !== undefined) {
        return schema.example;
    }

    return null;
};

const write = (fname, data) => {
    const yamlStr = yaml.dump(data, {
        noRefs: true,
        quotingType: "'",
        forceQuotes: false,
        indent: 2,
        lineWidth: -1,
        noArrayIndent: true,
        styles: {
            "!!int": "decimal",
            "!!float": "decimal",
        },
    });

    let formatted = yamlStr
        .replace(/createdAt: '(.+?)'/g, "createdAt: $1")
        .replace(/updatedAt: '(.+?)'/g, "updatedAt: $1")
        .replace(/description: ''/g, "description: ''")
        .replace(/value: '(.+?)'/g, "value: '$1'")
        .replace(/name: '(.+?)'/g, "name: $1")
        .replace(/sortPriority: (-?\d+)$/gm, "sortPriority: $1.0")
        .replace(/sortPriority: (-?\d+)\n/g, "sortPriority: $1.0\n");

    fs.writeFileSync(path.join(OUTPUT_DIR, fname), formatted);
};

// ----------  init ----------
if (!fs.existsSync(SPEC_FILE)) {
    console.error(`❌ Missing ${SPEC_FILE}`);
    process.exit(1);
}
if (fs.existsSync(OUTPUT_DIR)) fs.rmSync(OUTPUT_DIR, { recursive: true, force: true });
fs.mkdirSync(OUTPUT_DIR);

const spec = yaml.load(fs.readFileSync(SPEC_FILE, "utf8"));

// ----------  1️⃣ workspace ----------
const workspaceId = id("wk", WORKSPACE_NAME);
const workspace = {
    type: "workspace",
    model: "workspace",
    id: workspaceId,
    createdAt: NOW("2025-10-13"),
    updatedAt: NOW(),
    authentication: {},
    authenticationType: null,
    description: WORKSPACE_DESCRIPTION,
    headers: [],
    name: WORKSPACE_NAME,
    encryptionKeyChallenge: null,
    settingValidateCertificates: true,
    settingFollowRedirects: true,
    settingRequestTimeout: 0,
};
write(`yaak.${workspace.id}.yaml`, workspace);

// ----------  2️⃣ folders ----------
const tagFolders = {};
for (const tag of spec.tags || []) {
    const fid = id("fl", `folder:${tag.name}`);
    tagFolders[tag.name] = fid;

    let sortPriority = (spec.tags || []).indexOf(tag) * -100.0;

    const folder = {
        type: "folder",
        model: "folder",
        id: fid,
        createdAt: NOW("2025-10-13"),
        updatedAt: NOW(),
        workspaceId,
        folderId: null,
        authentication: {},
        authenticationType: null,
        description: tag.description || "",
        headers: [],
        name: tag.name,
        sortPriority: sortPriority == -0.0 ? 0.0 : sortPriority,
    };
    write(`yaak.${fid}.yaml`, folder);
}

// ----------  3️⃣ requests ----------
let requestIndex = 0;
for (const [url, methods] of Object.entries(spec.paths)) {
    for (const [method, op] of Object.entries(methods)) {
        const rid = id("rq", `${method}:${url}`);
        const folderId = tagFolders[op.tags?.[0]] || null;

        const yaakUrl = "${[ BASE_URL ]}" + url.replace(/{/g, ":").replace(/}/g, "");

        const urlParams = [];
        if (Array.isArray(op.parameters)) {
            for (const p of op.parameters) {
                if (p.in === "path") {
                    let exampleValue = "";
                    if (p.schema) {
                        if (p.schema.examples && p.schema.examples.length > 0) {
                            exampleValue = String(p.schema.examples[0]);
                        } else if (p.schema.example !== undefined) {
                            exampleValue = String(p.schema.example);
                        } else if (p.schema.default !== undefined) {
                            exampleValue = String(p.schema.default);
                        }
                    }

                    urlParams.push({
                        enabled: true,
                        name: `:${p.name}`,
                        value: exampleValue,
                        id: id("P", `${method}:${url}:path:${p.name}`),
                    });
                } else if (p.in === "query") {
                    let exampleValue = "";
                    if (p.schema) {
                        if (p.schema.examples && p.schema.examples.length > 0) {
                            exampleValue = String(p.schema.examples[0]);
                        } else if (p.schema.example !== undefined) {
                            exampleValue = String(p.schema.example);
                        } else if (p.schema.default !== undefined) {
                            exampleValue = String(p.schema.default);
                        }
                    }

                    urlParams.push({
                        enabled: true,
                        name: p.name,
                        value: exampleValue,
                        id: id("P", `${method}:${url}:query:${p.name}`),
                    });
                }
            }
        }

        // Extract body example from requestBody
        let bodyContent = {};
        let bodyType = "none";

        if (op.requestBody && op.requestBody.content) {
            const jsonContent = op.requestBody.content["application/json"];
            if (jsonContent && jsonContent.schema) {
                const example = getSchemaExample(jsonContent.schema, spec);
                if (example) {
                    bodyContent = { text: JSON.stringify(example, null, 2) };
                    bodyType = "application/json";
                }
            }
        }

        // Add Content-Type header for requests with JSON body
        const headers = [];
        if (bodyType === "application/json") {
            headers.push({
                enabled: true,
                name: "Content-Type",
                value: "application/json",
                id: id("H", `${method}:${url}:Content-Type`),
            });
        }

        let sortPriority = requestIndex * -100.0;

        const rq = {
            type: "http_request",
            model: "http_request",
            id: rid,
            createdAt: NOW("2025-10-13"),
            updatedAt: NOW(),
            workspaceId,
            folderId,
            authentication: {},
            authenticationType: null,
            body: bodyContent,
            bodyType: bodyType,
            description: op.description || "",
            headers: headers,
            method: method.toUpperCase(),
            name: op.operationId ? op.operationId.split("_")[1] : `${method.toUpperCase()} ${url}`,
            sortPriority: sortPriority === -0.0 ? 0.0 : sortPriority,
            url: yaakUrl,
            urlParameters: urlParams,
        };
        write(`yaak.${rid}.yaml`, rq);
        requestIndex++;
    }
}

console.log("✅ Done. Yaak workspace generated in ./yaak/");
